name: ovadrive
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  chat_gpt_sdk: ^1.0.2+4
  flutter_riverpod: ^2.1.3
  cupertino_icons: ^1.0.2
  speech_to_text: ^6.1.1
  firebase_core: ^2.8.0
  cloud_firestore: ^4.4.5
  flutter_tts: ^3.6.3
  porcupine_flutter: ^2.2.2
  wakelock: ^0.6.2
 
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
